Repository msfjarvis/compose-lobsters, pull requests merged in 2020-10, with the labels that each got.

#35 LobstersItem: replace ListItem with Column
  app/src/main/java/dev/msfjarvis/lobsters/MainActivity.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/LobstersItem.kt
Labels: automerge, bug

#37 Fallback to comments if post has no URL
  app/src/main/java/dev/msfjarvis/lobsters/MainActivity.kt
Labels: automerge, bug, enhancement

#38 build: extract all versions to ext
  app/build.gradle
  build.gradle
  lobsters-api/build.gradle
Labels: automerge

#39 app: add user avatars to items
  app/build.gradle
  app/src/main/java/dev/msfjarvis/lobsters/di/ApiModule.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/LobstersItem.kt
  build.gradle
Labels: automerge, enhancement

#40 Multiple improvements across the board
  .github/auto-merge.yml
  .github/workflows/automerge.yml
  .github/workflows/pull_request.yml
  app/src/main/java/dev/msfjarvis/lobsters/data/LobstersViewModel.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/LobstersItem.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/Theme.kt
  app/src/main/java/dev/msfjarvis/lobsters/urllauncher/UrlLauncherImpl.kt
Labels: automerge, enhancement

#44 Update dependencies
  app/src/main/java/dev/msfjarvis/lobsters/compose/utils/DeferredIcon.kt
  build.gradle
  gradle.properties
Labels: automerge

#45 Update all actions and pin to SHA1 hashes
  .github/workflows/automerge.yml
  .github/workflows/pull_request.yml
Labels: automerge

#43 Add saved messages feature
  app/src/main/java/dev/msfjarvis/lobsters/MainActivity.kt
  app/src/main/java/dev/msfjarvis/lobsters/compose/utils/DeferredIcon.kt
  app/src/main/java/dev/msfjarvis/lobsters/data/LobstersViewModel.kt
  app/src/main/java/dev/msfjarvis/lobsters/di/ApiModule.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/LobstersItem.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/Theme.kt
  app/src/main/res/drawable/ic_favorite_24px.xml
  app/src/main/res/drawable/ic_favorite_border_24px.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/dev/msfjarvis/lobsters/data/model/SavedLobstersEntity.kt
  data/src/main/java/dev/msfjarvis/lobsters/data/source/PostsDao.kt
  data/src/main/java/dev/msfjarvis/lobsters/data/source/PostsDatabase.kt
  data/src/main/java/dev/msfjarvis/lobsters/data/source/SavedPostsDao.kt
  lobsters-api/src/test/java/dev/msfjarvis/lobsters/api/TestUtils.kt
  model/src/main/java/dev/msfjarvis/lobsters/model/LobstersPost.kt
Labels: automerge, enhancement

#46 Upgrade dependencies
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: automerge, dependencies

#48 Enable minification of release builds
  app/build.gradle
  app/proguard-android-optimize.txt
  app/proguard-rules.pro
  gradle.properties
Labels: automerge

#50 Update coroutines and AGP
  build.gradle
  gradle.properties
Labels: dependencies

#51 Upgrade Browser and Compose
  app/src/main/java/dev/msfjarvis/lobsters/compose/utils/DeferredIcon.kt
  build.gradle
Labels: automerge

#52 Switch to BottomNav and use AndroidX navigation
  app/build.gradle
  app/src/main/java/dev/msfjarvis/lobsters/MainActivity.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/Destination.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/EmptyList.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/HottestPosts.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/SavedPosts.kt
  app/src/main/res/drawable/ic_whatshot_24px.xml
  build.gradle
Labels: enhancement
