Repository msfjarvis/compose-lobsters, pull requests merged in 2020-09, with the labels that each got.

#8 Update compose and AGP
  build.gradle
Labels: automerge

#9 Allow providing names for items
  .editorconfig
  app/build.gradle
  app/src/main/java/dev/msfjarvis/todo/MainActivity.kt
  app/src/main/java/dev/msfjarvis/todo/ui/TodoRow.kt
  app/src/main/java/dev/msfjarvis/todo/ui/TodoTheme.kt
  app/src/main/java/dev/msfjarvis/todo/ui/WireGuardItem.kt
Labels: automerge

#10 Fix theme colors
  app/src/main/java/dev/msfjarvis/todo/MainActivity.kt
  app/src/main/java/dev/msfjarvis/todo/ui/TodoTheme.kt
Labels: automerge

#11 Correctly enable now-fixed theming and tweak dialog layout
  app/src/main/java/dev/msfjarvis/todo/MainActivity.kt
  app/src/main/java/dev/msfjarvis/todo/ui/TodoTheme.kt
Labels: automerge, enhancement

#12 Increase test surface to cover more cases
  app/src/androidTest/java/dev/msfjarvis/todo/MainActivityTest.kt
  app/src/main/java/dev/msfjarvis/todo/MainActivity.kt
Labels: automerge, enhancement

#13 Modularize data package
  .idea/gradle.xml
  app/build.gradle
  build.gradle
  data/.gitignore
  data/build.gradle
  data/src/main/AndroidManifest.xml
  data/src/main/java/dev/msfjarvis/todo/data/model/TodoItem.kt
  data/src/main/java/dev/msfjarvis/todo/data/source/DateTimeTypeConverters.kt
  data/src/main/java/dev/msfjarvis/todo/data/source/TodoDatabase.kt
  data/src/main/java/dev/msfjarvis/todo/data/source/TodoItemDao.kt
  settings.gradle
Labels: automerge, enhancement

#14 Dependency updates
  .github/workflows/pull_request.yml
  app/build.gradle
  build.gradle
  data/build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: automerge

#15 Switch to Dagger Hilt for dependency injection
  app/build.gradle
  app/src/main/java/dev/msfjarvis/todo/Application.kt
  app/src/main/java/dev/msfjarvis/todo/MainActivity.kt
  app/src/main/java/dev/msfjarvis/todo/di/Graph.kt
  app/src/main/java/dev/msfjarvis/todo/di/PersistenceModule.kt
  build.gradle
Labels: automerge

#16 Optimize UI and UX for URLs
  .idea/codeStyles/Project.xml
  app/src/androidTest/java/dev/msfjarvis/todo/MainActivityTest.kt
  app/src/main/java/dev/msfjarvis/todo/Application.kt
  app/src/main/java/dev/msfjarvis/todo/MainActivity.kt
  app/src/main/java/dev/msfjarvis/todo/di/UrlLauncherModule.kt
  app/src/main/java/dev/msfjarvis/todo/ui/TodoRow.kt
  app/src/main/java/dev/msfjarvis/todo/urllauncher/UrlLauncher.kt
  app/src/main/java/dev/msfjarvis/todo/urllauncher/UrlLauncherImpl.kt
  app/src/main/res/drawable/ic_delete_forever_24dp.xml
  gradle.properties
Labels: automerge, enhancement

#17 build: update Compose
  app/src/androidTest/java/dev/msfjarvis/todo/MainActivityTest.kt
  build.gradle
Labels: automerge

#18 Add swipe dismiss
  app/build.gradle
  app/src/main/java/dev/msfjarvis/todo/MainActivity.kt
  app/src/main/java/dev/msfjarvis/todo/ui/AnimatedSwipeDismiss.kt
  app/src/main/java/dev/msfjarvis/todo/ui/ListContent.kt
  app/src/main/java/dev/msfjarvis/todo/ui/TodoRow.kt
  app/src/main/res/drawable/ic_delete_forever_24dp.xml
  build.gradle
Labels: automerge, enhancement

#19 build: update gradle properties
  gradle.properties
Labels: automerge, enhancement

#21 Use retrofit suspend support to hide implementation details of API
  app/src/main/java/dev/msfjarvis/lobsters/MainActivity.kt
  lobsters-api/build.gradle
  lobsters-api/src/main/java/dev/msfjarvis/lobsters/api/LobstersApi.kt
  lobsters-api/src/test/java/dev/msfjarvis/lobsters/api/LobstersApiTest.kt
Labels: automerge, enhancement

#22 Add pagination support for infinite scrolling
  app/build.gradle
  app/src/main/java/dev/msfjarvis/lobsters/MainActivity.kt
  app/src/main/java/dev/msfjarvis/lobsters/data/LobstersViewModel.kt
  app/src/main/java/dev/msfjarvis/lobsters/di/PersistenceModule.kt
  build.gradle
  data/build.gradle
  data/src/main/java/dev/msfjarvis/lobsters/data/source/LobstersApiTypeConverters.kt
  data/src/main/java/dev/msfjarvis/lobsters/data/source/PostsDao.kt
  data/src/main/java/dev/msfjarvis/lobsters/data/source/PostsDatabase.kt
  lobsters-api/build.gradle
  lobsters-api/src/main/java/dev/msfjarvis/lobsters/api/LobstersApi.kt
  lobsters-api/src/test/java/dev/msfjarvis/lobsters/api/LobstersApiTest.kt
  model/build.gradle
  model/src/main/java/dev/msfjarvis/lobsters/model/Submitter.kt
Labels: automerge, enhancement

#23 Use consistent vertical padding
  app/src/main/java/dev/msfjarvis/lobsters/ui/LobstersItem.kt
Labels: automerge, enhancement

#24 Make row UI better match lobste.rs
  app/src/main/java/dev/msfjarvis/lobsters/ui/LobstersItem.kt
Labels: enhancement

#25 Perf and UX improvements
  app/build.gradle
  app/src/main/java/dev/msfjarvis/lobsters/Application.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/LobstersItem.kt
  app/src/main/java/dev/msfjarvis/lobsters/urllauncher/UrlLauncherImpl.kt
Labels: automerge, enhancement

#26 Cure a case of leaky abstractions with sad indirection
  build.gradle
  data/src/main/java/dev/msfjarvis/lobsters/data/model/LobstersEntity.kt
  data/src/main/java/dev/msfjarvis/lobsters/data/source/PostsDao.kt
  data/src/main/java/dev/msfjarvis/lobsters/data/source/PostsDatabase.kt
  gradle/wrapper/gradle-wrapper.properties
  model/build.gradle
  model/src/main/java/dev/msfjarvis/lobsters/model/LobstersPost.kt
Labels: automerge

#27 Add comment open action and cleanup unused code
  app/src/main/AndroidManifest.xml
  app/src/main/java/dev/msfjarvis/lobsters/MainActivity.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/LobstersItem.kt
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  data/src/main/java/dev/msfjarvis/lobsters/data/source/DateTimeTypeConverters.kt
  data/src/main/java/dev/msfjarvis/lobsters/data/source/LobstersApiTypeConverters.kt
  data/src/main/java/dev/msfjarvis/lobsters/data/source/PostsDatabase.kt
Labels: automerge, enhancement

#31 Set up offline caching and no posts state
  app/src/main/java/dev/msfjarvis/lobsters/MainActivity.kt
  app/src/main/java/dev/msfjarvis/lobsters/data/LobstersViewModel.kt
  app/src/main/res/drawable/ic_sync_problem_24px.xml
  app/src/main/res/values/strings.xml
  data/src/main/java/dev/msfjarvis/lobsters/data/source/PostsDao.kt
Labels: automerge, enhancement

#32 Clear local cache of posts on first load
  app/src/main/java/dev/msfjarvis/lobsters/data/LobstersViewModel.kt
Labels: automerge, enhancement
