Repository msfjarvis/compose-lobsters, pull requests merged in 2021-05, with the labels that each got.

#239 Add FAB animation
  app/src/main/java/dev/msfjarvis/lobsters/ui/comments/Comments.kt
Labels: area: android, enhancement

#241 Bump JB Compose
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
Labels: area: android, area: desktop, dependencies

#244 AndroidX update day
  gradle/libs.versions.toml
Labels: dependencies

#249 Remove duplicate UrlLauncher from desktop
  desktop/src/jvmMain/kotlin/dev/msfjarvis/lobsters/ui/LobstersItem.kt
  desktop/src/jvmMain/kotlin/dev/msfjarvis/lobsters/util/UrlLauncher.kt
Labels: area: desktop

#252 Handle lobste.rs deeplinks in the app
  app/src/main/AndroidManifest.xml
  app/src/main/java/dev/msfjarvis/lobsters/ui/comments/Comments.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/main/LobstersApp.kt
Labels: area: android, enhancement
