Repository msfjarvis/compose-lobsters, pull requests merged in 2021-04, with the labels that each got.

#181 Update JB Compose and Moshi
  app/build.gradle.kts
  bors.toml
  buildSrc/src/main/java/Dependencies.kt
  common/build.gradle.kts
  desktop/build.gradle.kts
Labels: dependencies

#183 Sort saved posts months as well
  app/src/main/java/dev/msfjarvis/lobsters/ui/posts/SavedPosts.kt
Labels: area: android, bug

#185 Preserve backstack in navigation
  app/src/main/java/dev/msfjarvis/lobsters/ui/main/LobstersApp.kt
Labels: area: android, enhancement

#186 Simplify ordering logic
  app/src/main/java/dev/msfjarvis/lobsters/ui/posts/SavedPosts.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: area: android, bug

#165 Allow backup and restore of saved posts
  .idea/artifacts/database_jvm.xml
  app/build.gradle.kts
  app/src/androidTest/java/dev/msfjarvis/lobsters/ui/main/LobstersTopBarTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/dev/msfjarvis/lobsters/data/backup/BackupHandler.kt
  app/src/main/java/dev/msfjarvis/lobsters/injection/BackupModule.kt
  app/src/main/java/dev/msfjarvis/lobsters/injection/DatabaseModule.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/main/LobstersApp.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/main/LobstersTopAppBar.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/settings/Options.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/settings/Settings.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/settings/SettingsActivity.kt
  app/src/main/res/drawable/ic_app_settings_24px.xml
  common/src/androidMain/kotlin/dev/msfjarvis/lobsters/utils/StringValue.kt
  common/src/androidMain/res/values/strings.xml
  common/src/commonMain/kotlin/dev/msfjarvis/lobsters/utils/Strings.kt
  common/src/jvmMain/kotlin/dev/msfjarvis/lobsters/utils/StringValue.kt
  database/build.gradle.kts
  database/src/androidMain/AndroidManifest.xml
  database/src/androidMain/kotlin/dev/msfjarvis/lobsters/data/local/Database.kt
  database/src/commonMain/kotlin/dev/msfjarvis/lobsters/data/local/Database.kt
  database/src/commonMain/kotlin/dev/msfjarvis/lobsters/data/model/TagsAdapter.kt
  database/src/commonMain/sqldelight/dev/msfjarvis/lobsters/data/local/SavedPost.sq
  database/src/jvmMain/kotlin/dev/msfjarvis/lobsters/data/local/Database.kt
  database/src/jvmTest/kotlin/dev/msfjarvis/lobsters/data/local/SqlDelightQueriesTest.kt
Labels: area: android, enhancement

#188 Bump JetBrains Compose
  app/build.gradle.kts
  buildSrc/src/main/java/Dependencies.kt
  common/build.gradle.kts
  desktop/build.gradle.kts
Labels: area: android, area: desktop, dependencies

#190 Sort build dependencies
  buildSrc/src/main/java/BaseProjectConfig.kt
  buildSrc/src/main/java/Dependencies.kt
  common/build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
Labels: area: android, area: desktop, dependencies

#191 Update Compose, Dagger and KSP
  api/build.gradle.kts
  app/build.gradle.kts
  app/src/main/java/dev/msfjarvis/lobsters/ui/settings/Options.kt
  buildSrc/src/main/java/Dependencies.kt
  common/build.gradle.kts
  desktop/build.gradle.kts
Labels: area: android, dependencies

#193 Update JetBrains Compose
  buildSrc/src/main/java/Dependencies.kt
Labels: area: android, area: desktop, dependencies

#194 Improve dependency organization
  app/build.gradle.kts
  common/build.gradle.kts
  desktop/build.gradle.kts
  desktop/src/jvmMain/kotlin/dev/msfjarvis/lobsters/data/ApiRepository.kt
  desktop/src/jvmMain/kotlin/dev/msfjarvis/lobsters/ui/LobstersItem.kt
  desktop/src/jvmMain/kotlin/dev/msfjarvis/lobsters/ui/Main.kt
  desktop/src/jvmMain/kotlin/dev/msfjarvis/lobsters/ui/Theme.kt
  desktop/src/jvmMain/kotlin/dev/msfjarvis/lobsters/util/UrlLauncher.kt
Labels: area: android, area: desktop, dependencies

#195 Bump AGP and Gradle
  app/build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/BaseProjectConfig.kt
  buildSrc/src/main/java/Dependencies.kt
  desktop/build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
Labels: area: android, area: desktop, dependencies

#201 Use secondary color variant for tag background
  app/src/main/java/dev/msfjarvis/lobsters/ui/posts/LobstersItem.kt
Labels: area: android

#202 Force refresh post cache after importing saved posts
  app/src/main/java/dev/msfjarvis/lobsters/data/backup/BackupHandler.kt
  app/src/main/java/dev/msfjarvis/lobsters/data/repo/LobstersRepository.kt
  app/src/main/java/dev/msfjarvis/lobsters/injection/BackupModule.kt
Labels: area: android, bug

#205 Protect against database thrashing by paging
  app/src/main/java/dev/msfjarvis/lobsters/data/backup/BackupHandler.kt
  app/src/main/java/dev/msfjarvis/lobsters/data/remote/HottestPostsPagingSource.kt
  app/src/main/java/dev/msfjarvis/lobsters/data/remote/LobstersPagingSource.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/viewmodel/LobstersViewModel.kt
Labels: area: android

#206 Handle network errors in comments view
  app/src/main/java/dev/msfjarvis/lobsters/ui/comments/Comments.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/main/LobstersApp.kt
Labels: area: android, bug

#210 Bump Dagger and JetBrains Compose
  buildSrc/src/main/java/Dependencies.kt
Labels: dependencies

#212 Fix submitter name color in dark mode
  app/src/main/java/dev/msfjarvis/lobsters/ui/comments/CommentEntry.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/comments/Comments.kt
Labels: area: android, bug

#215 Fix refresh action
  app/src/main/java/dev/msfjarvis/lobsters/ui/viewmodel/LobstersViewModel.kt
Labels: area: android, bug

#218 Bump JB Compose to 0.4.0-build184
  gradle/libs.versions.toml
Labels: dependencies

#221 Update dependencies
  app/build.gradle.kts
  app/src/main/java/com/puculek/pulltorefresh/PullToRefresh.kt
  app/src/main/java/com/puculek/pulltorefresh/PullToRefreshProgressIndicator.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/posts/LobstersItem.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/posts/NetworkPosts.kt
  gradle/libs.versions.toml
Labels: area: android, dependencies

#222 Tie refresh state with Paging
  app/src/main/java/dev/msfjarvis/lobsters/ui/posts/NetworkPosts.kt
Labels: area: android

#223 Bump KSP to 1.4.32-1.0.0-alpha08
  gradle/libs.versions.toml
Labels: dependencies

#224 Increase SwipeRefreshIndicator elevation
  app/src/main/java/dev/msfjarvis/lobsters/ui/posts/LobstersItem.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/posts/NetworkPosts.kt
  buildSrc/src/main/java/BaseProjectConfig.kt
Labels: area: android, enhancement

#225 Bump Dagger and Hilt to 2.35
  gradle/libs.versions.toml
Labels: dependencies

#228 Bump Accompanist to 0.8.1
  app/src/main/java/dev/msfjarvis/lobsters/ui/posts/NetworkPosts.kt
  gradle/libs.versions.toml
Labels: area: android, dependencies

#229 Update SQLDelight to 1.5.0
  gradle/libs.versions.toml
Labels: area: android, dependencies

#227 Track comment parents via colored lines
  app/src/main/java/dev/msfjarvis/lobsters/ui/comments/CommentEntry.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/comments/CommentTreeColor.kt
  app/src/main/java/dev/msfjarvis/lobsters/ui/comments/Comments.kt
Labels: area: android, enhancement

#236 Bump JB Compose to 0.4.0-build185
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
Labels: area: android, area: desktop, enhancement

#237 Bump Dagger
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
Labels: dependencies

#238 Bump to AGP 7.0.0-alpha15
  app/build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/BaseProjectConfig.kt
  gradle/libs.versions.toml
  scripts/deploy-snapshot.sh
Labels: area: android
